name: main
on: [push]

jobs:

  build-and-test-node14:
    runs-on: ubuntu-20.04
    name: Node14
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: .github/test/package-lock.json
      - run: npm install --prefix .github/test
      - run: npm test --prefix .github/test
    
    tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress info
        uses: ./
        with:
          build: npx cypress info
          working-directory: /.